(* ::Package:: *)

(************************************************************************)\012(* This file was generated automatically by the Mathematica front end.  *)\012(* It contains Initialization cells from a Notebook file, which         *)\012(* typically will have the same name as this file except ending in      *)\012(* ".nb" instead of ".m".                                               *)\012(*                                                                      *)\012(* This file is intended to be loaded into the Mathematica kernel using *)\012(* the package loading commands Get or Needs.  Doing so is equivalent   *)\012(* to using the Evaluate Initialization Cells menu command in the front *)\012(* end.                                                                 *)\012(*                                                                      *)\012(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)\012(* automatically each time the parent Notebook file is saved in the     *)\012(* Mathematica front end.  Any changes you make to this file will be    *)\012(* overwritten.                                                         *)\012(************************************************************************)\012\012

(* ::Input::Initialization:: *)
sMat = {{s11[t],s12[t],s13[t]},{s12[t],s22[t],s23[t]},{s13[t],s23[t],s33[t]}};
tauMat = {{tau11[t],tau12[t],tau13[t]},{tau12[t],tau22[t],tau23[t]},{tau13[t],tau23[t],tau33[t]}};
dU = {{u11[t],u12[t],u13[t]},{u21[t],u22[t],u23[t]},{u31[t],u32[t],u33[t]}};
extraStressSolveFunctionList = {tau11[t],tau22[t],tau33[t],tau12[t],tau13[t],tau23[t]};
strainSolveFunctionList = {s11[t],s22[t],s33[t],u12[t],s13[t],s23[t]};
gMat = 1/2(dU+Transpose[dU]);
extraStressSolveComponentList =D[extraStressSolveFunctionList,t];
strainSolveComponentList = D[strainSolveFunctionList,t];
zeroNonShearStrainRateList ={u11[t]->0,u22[t]->0,u33[t]->0,u23[t]->0,u13[t]->0,u31[t]->0,u32[t]->0,u21[t]->0};
zeroNonShearStrainDerivativeList = D[zeroNonShearStrainRateList,t];
zeroNonShearStrainRuleList = Join[zeroNonShearStrainRateList,zeroNonShearStrainDerivativeList];
(*Set of rules to convert expression in extra stress variable to an expression in total stress variable*)
extraStressRules = Flatten@MapThread[{#1->#2-solventViscosity*#3,D[#1,t]->D[#2-solventViscosity*#3,t]}&,{Flatten[tauMat],Flatten[sMat],Flatten[gMat]}]//DeleteDuplicates;


(* ::Input::Initialization:: *)
camelToSnake[camel_String]:=Module[{s1,snake},s1=StringReplace[camel,RegularExpression["(.)([A-Z][a-z]+)"]:>"$1_$2"];
snake=StringReplace[s1,RegularExpression["([a-z0-9])([A-Z])"]:>"$1_$2"];
ToLowerCase[snake]]
toPythonSyntax[expr_,name_:""]:=Module[{intermediateExpr,intermediateExpr2},
intermediateExpr =FullSimplify[expr/. {Derivative[1][func_][t]:>Symbol["d"<>ToString[func]],func_[t]:>func}]; intermediateExpr2=StringReplace[ToString[intermediateExpr,InputForm],{"Sqrt"->"jnp.sqrt","E^"->"jnp.exp","^"->"**","["->"(","]"->")","{"->"","}"->"","\n"->""," "->"","->"->"=",RegularExpression[","]->"\n"}];
If[name!="","# "<>name<>"\n",""]<>camelToSnake[intermediateExpr2]]
solveForViscoelasticEquations[LHS_,RHS_,name_:"",toStringExpr_:True]:=Module[{extraStressEqn,totalStressEqn,extraStressSol,totalStressSol},
extraStressEqn=LHS==RHS;
extraStressSol =FullSimplify[Cancel[ Solve[extraStressEqn,extraStressSolveComponentList]]];
totalStressEqn=(extraStressEqn/.extraStressRules/.zeroNonShearStrainRuleList);
totalStressSol=FullSimplify[Cancel[Solve[totalStressEqn,strainSolveComponentList]]];
If[toStringExpr==True,
{{toPythonSyntax[extraStressSol,If[name!="",name<>" extra stress",""]]},{toPythonSyntax[totalStressSol,If[name!="",name<>" strain solution",""]]}},
{extraStressSol,totalStressSol}]
]


(* ::Input::Initialization:: *)
oldroydBExtraStressLHS = tauMat + relaxationTime*(D[tauMat,t]-tauMat . dU-Transpose[dU] . tauMat);
oldroydBExtraStressRHS = polymerViscosity*gMat;
oldroydBEquationStrings =solveForViscoelasticEquations[oldroydBExtraStressLHS,oldroydBExtraStressRHS,"Oldroyd-B"];


(* ::Input::Initialization:: *)
giesekusLHS = tauMat + relaxationTime*(D[tauMat,t]-tauMat . dU-Transpose[dU] . tauMat)+alpha *relaxationTime/polymerViscosity*tauMat . tauMat;
giesekusRHS = polymerViscosity*gMat;
giesekusEquationStrings = solveForViscoelasticEquations[giesekusLHS,giesekusRHS,"Giesekus"];


(* ::Input::Initialization:: *)
PTTLinearLHS = (1+epsilon relaxationTime/polymerViscosity Tr[tauMat])tauMat + relaxationTime *(D[tauMat,t]-tauMat . dU-Transpose[dU] . tauMat +zeta(tauMat . gMat+gMat . tauMat));
PTTLinearRHS = polymerViscosity*gMat;
PTTLinearEquationStrings=solveForViscoelasticEquations[PTTLinearLHS,PTTLinearRHS,"PTT Linear"];


(* ::Input::Initialization:: *)
PTTExponentialLHS = Exp[epsilon relaxationTime/polymerViscosity Tr[tauMat]]tauMat + relaxationTime *(D[tauMat,t]-tauMat . dU-Transpose[dU] . tauMat +zeta(tauMat . gMat+gMat . tauMat));
PTTExponentialRHS = polymerViscosity*gMat;
PTTExponentialEquationStrings=solveForViscoelasticEquations[PTTExponentialLHS,PTTExponentialRHS,"PTT Exponential"];


(* ::Input::Initialization:: *)
PTTGeneralLHS = fPTT*tauMat + relaxationTime *(D[tauMat,t]-tauMat . dU-Transpose[dU] . tauMat +zeta(tauMat . gMat+gMat . tauMat));
PTTGeneralRHS = polymerViscosity*gMat;
PTTGeneralEquationStrings=solveForViscoelasticEquations[PTTGeneralLHS,PTTGeneralRHS,"PTT General"];


(* ::Input::Initialization:: *)
FTensor = {{F11,F12,F13},{F12,F22,F23},{F13,F23,F33}};
FFormExtraStressLHS =  tauMat + relaxationTime*(D[tauMat,t]-tauMat . dU-Transpose[dU] . tauMat)+FTensor;
FFormExtraStressRHS =polymerViscosity*gMat;
FFormEquationStrings = solveForViscoelasticEquations[FFormExtraStressLHS,FFormExtraStressRHS,"F Form"];


(* ::Input::Initialization:: *)
fFENECR= (extensionLength^2 + relaxationTime/polymerViscosity * Tr[tauMat])/(extensionLength^2 - 3);
FENECRLHS = (1+relaxationTime D[1/fFENECR,t])tauMat + relaxationTime/fFENECR *(D[tauMat,t]-tauMat . dU-Transpose[dU] . tauMat);
FENECRRHS = polymerViscosity*gMat;
FENECREquationStrings = solveForViscoelasticEquations[FENECRLHS,FENECRRHS,"FENE CR"];


(* ::Input::Initialization:: *)
aFENEP=extensionLength^2/(extensionLength^2 -3);
fFENEP= (extensionLength^2 + relaxationTime/(aFENEP*polymerViscosity) * Tr[tauMat])/(extensionLength^2 - 3);
FENEPLHS = tauMat+relaxationTime/fFENEP*(D[tauMat,t]-tauMat . dU-Transpose[dU] . tauMat);
FENEPRHS = aFENEP/fFENEP*polymerViscosity*gMat - D[1/fFENEP,t](relaxationTime*tauMat+aFENEP*polymerViscosity*IdentityMatrix[3]);
FENEPEquationStrings = solveForViscoelasticEquations[FENEPLHS,FENEPRHS,"FENE P"];


(* ::Input::Initialization:: *)
lambdaPomPom = Sqrt[1+Tr[tauMat]/(3*polymerViscosity/relaxationTime)];
fPomPom= 2relaxationTime/relaxationTimeS Exp[2/q*(lambdaPomPom-1)](1-1/lambdaPomPom^(n+1))+1/lambdaPomPom^2(1-alpha/3*Tr[tauMat . tauMat]/(polymerViscosity/relaxationTime)^2);
XPomPomLHS = fPomPom*tauMat + relaxationTime*(D[tauMat,t]-tauMat . dU-Transpose[dU] . tauMat)+alpha*relaxationTime/polymerViscosity*(tauMat . tauMat)+polymerViscosity/relaxationTime*(fPomPom-1)*IdentityMatrix[3];
XPomPomRHS = polymerViscosity*gMat;
XPomPomEquationStrings = solveForViscoelasticEquations[XPomPomLHS,XPomPomRHS,"XPomPom"];


(* ::Input::Initialization:: *)
chi = Sqrt[Tr[tauMat]/3];
k=(3-chi^2/chiMax^2)*(1-1/chiMax^2)/((1-chi^2/chiMax^2)*(3-1/chiMax^2))//FullSimplify;
RoliePolyLHS = relaxationTime*(D[tauMat,t]-tauMat . dU-Transpose[dU] . tauMat);
RoliePolyRHS = -(tauMat-IdentityMatrix[3])-2*k*relaxationTime/relaxationTimeR*(1-Sqrt[3/Tr[tauMat]])(tauMat + beta*((Tr[tauMat]/3)^delta)*(tauMat-IdentityMatrix[3]));
functionStringList = ToString[#/.{func_[t]:>func},InputForm]&/@extraStressSolveFunctionList;
stringReplacementList = Flatten[{#->"A"<>StringTake[#,{4,5}]}&/@functionStringList];
RoliePolyEquationStrings = solveForViscoelasticEquations[RoliePolyLHS,RoliePolyRHS,"Rolie Poly"];
RoliePolyEquationStrings[[1,1]]=StringReplace[RoliePolyEquationStrings[[1,1]],stringReplacementList];
RoliePolyEquationStrings[[2]]={};


(* ::Input::Initialization:: *)
(*pattern="*EquationStrings";
outputStrings=Flatten[ToExpression[Names[pattern]]];*)
outputStrings={oldroydBEquationStrings,giesekusEquationStrings,PTTLinearEquationStrings,PTTExponentialEquationStrings,PTTGeneralEquationStrings,FFormEquationStrings,FENECREquationStrings,FENEPEquationStrings,XPomPomEquationStrings,RoliePolyEquationStrings};
outputStringFormatted =StringTrim[StringJoin@@(#<>"\n\n"&/@Flatten[outputStrings])];
Export["viscoelastic_models.txt",outputStringFormatted];



